//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaptItAcademy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int ID { get; set; }
        public string Venue { get; set; }
        public int CourseID { get; set; }
        public int NumberOfSits { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<decimal> TrainingCost { get; set; }
        public System.DateTime RegClosingDate { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
